#include "token_type.h"

#include <unordered_map>

std::string toString(const TokenType& tokenType) {
    static const std::unordered_map<TokenType, std::string> tokenStrings = {
        {END_OF_FILE, "EOF"},
        {NEWLINE, "NEWLINE"},
        {IMMEDIATE, "IMMEDIATE"},
        {INDENT, "INDENT"},
        {COMMA, "COMMA"},
        {DESTINATION_REGISTER, "DESTINATION_REGISTER"},
        {SOURCE_REGISTER, "SOURCE_REGISTER"},
        {SOURCE_REGISTER_2, "SOURCE_REGISTER_2"},

        {X0, "x0"},
        {X1, "x1"},
        {X2, "x2"},
        {X3, "x3"},
        {X4, "x4"},
        {X5, "x5"},
        {X6, "x6"},
        {X7, "x7"},
        {X8, "x8"},
        {X9, "x9"},
        {X10, "x10"},
        {X11, "x11"},
        {X12, "x12"},
        {X13, "x13"},
        {X14, "x14"},
        {X15, "x15"},
        {X16, "x16"},
        {X17, "x17"},
        {X18, "x18"},
        {X19, "x19"},
        {X20, "x20"},
        {X21, "x21"},
        {X22, "x22"},
        {X23, "x23"},
        {X24, "x24"},
        {X25, "x25"},
        {X26, "x26"},
        {X27, "x27"},
        {X28, "x28"},
        {X29, "x29"},
        {X30, "x30"},
        {X31, "x31"},

        {ZERO, "zero"},
        {RA, "ra"},
        {SP, "sp"},
        {TP, "tp"},
        {T0, "t0"},
        {T1, "t1"},
        {T2, "t2"},
        {T3, "t3"},
        {T4, "t4"},
        {T5, "t5"},
        {T6, "t6"},
        {S0, "s0"},
        {S1, "s1"},
        {S2, "s2"},
        {S3, "s3"},
        {S4, "s4"},
        {S5, "s5"},
        {S6, "s6"},
        {S7, "s7"},
        {S8, "s8"},
        {S9, "s9"},
        {S10, "s10"},
        {S11, "s11"},
        {A0, "a0"},
        {A1, "a1"},
        {A2, "a2"},
        {A3, "a3"},
        {A4, "a4"},
        {A5, "a5"},
        {A6, "a6"},
        {A7, "a7"},

        {ADD, "ADD"},
        {SUB, "SUB"},
        {SLL, "SLL"},
        {SLT, "SLT"},
        {SLTU, "SLTU"},
        {XOR, "XOR"},
        {SRL, "SRL"},
        {SRA, "SRA"},
        {OR, "OR"},
        {AND, "AND"},
        {MUL, "MUL"},
        {DIV, "DIV"},
        {REM, "REM"},

        {ADDI, "ADDI"},
        {SLTI, "SLTI"},
        {SLTIU, "SLTIU"},
        {XORI, "XORI"},
        {ORI, "ORI"},
        {ANDI, "ANDI"},
        {SLLI, "SLLI"},
        {SRLI, "SRLI"},
        {SRAI, "SRAI"},
        {LB, "LB"},
        {LH, "LH"},
        {LW, "LW"},
        {LBU, "LBU"},
        {LHU, "LHU"},
        {JALR, "JALR"},

        {SB, "SB"},
        {SH, "SH"},
        {SW, "SW"},

        {BEQ, "BEQ"},
        {BNE, "BNE"},
        {BLT, "BLT"},
        {BGE, "BGE"},
        {BLTU, "BLTU"},
        {BGEU, "BGEU"},

        {LUI, "LUI"},
        {AUIPC, "AUIPC"},

        {JAL, "JAL"},
    };

    auto it = tokenStrings.find(tokenType);
    if (it != tokenStrings.end()) {
        return it->second;
    }
    return "UNKNOWN";
}
