load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "memory_test",
    srcs = [
        "memory_test.cc"
    ],
    deps = [
        "//src/devices:memory",
        "@googletest//:gtest_main"
    ]
)
