load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "exceptions",
    hdrs = [
        "bus_exception.h",
        "decode_exception.h",
        "device_exception.h",
        "memory_exception.h",
        "register_file_exception.h",
    ],
    visibility = ["//visibility:public"],
)
