load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    hdrs = ["constants.h"],
    visibility = ["//visibility:public"],
    deps = ["types"]
)

cc_library(
    name = "types",
    hdrs = ["types.h"]
)